### PR TITLE
[Bug Fix] Fix incomplete translations

### PR DESCRIPTION
**Pull request by jacklightChen**
### Problem Summary
Fix incomplete translations for users not logged in  (mobile only)

### Bug Report
WX20220318-130438@2x

### Code Change
```js
"fof-nightmode.forum.header.nightmode_button":"Toggle forum theme"
=====>
"fof-nightmode.forum.header.nightmode_button":"\u5207\u6362\u8bba\u575b\u4e3b\u9898"
```
### Contribution
Forum id: jacklight (wanna a beautiful Badge _(:з」∠)_)

### CODE REVIEW

**Comment by SignorMercurio** [comment]
Thank you for your contribution!

**Comment by cubercsl** [comment]
Missing translations can also be directly contributed to upstream https://github.com/flarum-lang/chinese-simplified .

Editing js files directly doesn't seem to be very maintainable.

We can synchronize translations when upstream project has a new stable release.

**Comment by jacklightChen** [comment]
@cubercsl Yeah, i know it's not maintainable (just for badge, bro = =). 
I think they may maintain a copy of this i18n repo for future dev instead of relying the outdated, hardly customized upstream to generate the files.

**Comment by panini519** [comment]
[新增贴内分享（链接卡片 / 图片）](https://trello.com/c/SSa4n8jc/35-%E6%96%B0%E5%A2%9E%E8%B4%B4%E5%86%85%E5%88%86%E4%BA%AB%EF%BC%88%E9%93%BE%E6%8E%A5%E5%8D%A1%E7%89%87-%E5%9B%BE%E7%89%87%EF%BC%89)

**Pull request merged**
